-- DropForeignKey
ALTER TABLE "MPP" DROP CONSTRAINT "MPP_userId_fkey";

-- AlterTable
ALTER TABLE "MPP" ALTER COLUMN "userId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "MPP" ADD CONSTRAINT "MPP_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
